name: Scan Python Code using Bandit

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      - name: python bandit
        run: |
            pip install bandit
            bandit -ll -ii -r .

      - name: Create Bandit Issue
        uses: octokit/request-action@v2.1
        if: always()
        with:
          route: POST /repos/${{ github.repository }}/issues
          headers: |
            Authorization: ${{ secrets.GITHUB_TOKEN }}
          data: |
            {
              "title": "Bandit Security Report",
              "body": "$(cat bandit-report.txt)"
            }

   